### ISSUE TITLE
Reboot Version

### ISSUE THREAD

**Issue by testpuddle** [motoko-bootcamp/you#2]
Suggestion we add a reboot_supported_standards field similar to ICRC1 and ICRC7.

For example stable var reboot_supported_standards as an array and a corresponding public function.

We went from a reboot "you" basic, to one that now has additional services.  Some of the deployed reboot canisters have implemented version 1, now others are running on version 2, 2+, etc.

I think we need to have the ability to enumerate what "feature set" a deployed canister has.

**Comment by seb-icp** [comment]
Great suggestion Ted. 

That also means we need to keep track of the versions somewhere. Let's do it.
