### ISSUE TITLE
Automatic mutual friendship

### ISSUE THREAD

**Issue by stefanlatinovic** [motoko-bootcamp/you#4]
For instance, when canister A sends a friend request to canister B, and it's accepted, canister B doesn't need to send a friend request back to canister A. After acceptance, both canisters become friends with each other without requiring any further action.

But is it fair to only friend requester spend cycles in that case? Should the cycles be spent equally between both canisters?

**Comment by Gymnopediese** [comment]
The relationship will now be its own canister so there will be a lot mutual stuff going on...
